const artData = [
  { id: 'vangogh1', imageUrl: 'Bilder/Vangogh1.jpg', artist: 'Van Gogh' },
  { id: 'vangogh2', imageUrl: 'Bilder/Vangogh2.png', artist: 'Van Gogh' },
  { id: 'vangogh3', imageUrl: 'Bilder/Vangogh3.jpg', artist: 'Van Gogh' },
  { id: 'vangogh4', imageUrl: 'Bilder/Vangogh4.png', artist: 'Van Gogh' },
  { id: 'vangogh5', imageUrl: 'Bilder/Vangogh5.jpg', artist: 'Van Gogh' },
  { id: 'vangogh6', imageUrl: 'Bilder/Vangogh6.jpg', artist: 'Van Gogh' },
  { id: 'vangogh7', imageUrl: 'Bilder/Vangogh7.jpg', artist: 'Van Gogh' },
  { id: 'vangogh8', imageUrl: 'Bilder/Vangogh8.jpg', artist: 'Van Gogh' },
  { id: 'vangogh9', imageUrl: 'Bilder/Vangogh9.jpg', artist: 'Van Gogh' },
  { id: 'vangogh10', imageUrl: 'Bilder/Vangogh10.jpg', artist: 'Van Gogh' },

  { id: 'michelangelo1', imageUrl: 'Bilder/michelangelo1.jpg', artist: 'Michelangelo' },
  { id: 'michelangelo2', imageUrl: 'Bilder/michelangelo2.jpg', artist: 'Michelangelo' },
  { id: 'michelangelo3', imageUrl: 'Bilder/michelangelo3.jpg', artist: 'Michelangelo' },
  { id: 'michelangelo4', imageUrl: 'Bilder/michelangelo4.jpg', artist: 'Michelangelo' },
  { id: 'michelangelo5', imageUrl: 'Bilder/michelangelo5.jpg', artist: 'Michelangelo' },
  { id: 'michelangelo6', imageUrl: 'Bilder/michelangelo6.jpg', artist: 'Michelangelo' },

  { id: 'leonardodavinci1', imageUrl: 'Bilder/leonardodavinci1.jpg', artist: 'Leonardo Da Vinci' },
  { id: 'leonardodavinci2', imageUrl: 'Bilder/leonardodavinci2.jpg', artist: 'Leonardo Da Vinci' },
  { id: 'leonardodavinci3', imageUrl: 'Bilder/leonardodavinci3.jpg', artist: 'Leonardo Da Vinci' },
  { id: 'leonardodavinci4', imageUrl: 'Bilder/leonardodavinci4.jpg', artist: 'Leonardo Da Vinci' },
  { id: 'leonardodavinci5', imageUrl: 'Bilder/leonardodavinci5.jpg', artist: 'Leonardo Da Vinci' },
  { id: 'leonardodavinci6', imageUrl: 'Bilder/leonardodavinci6.jpg', artist: 'Leonardo Da Vinci' },

  { id: 'claudemonet1', imageUrl: 'Bilder/claudemonet1.jpg', artist: 'Claude Monet' },
  { id: 'claudemonet2', imageUrl: 'Bilder/claudemonet2.jpg', artist: 'Claude Monet' },
  { id: 'claudemonet3', imageUrl: 'Bilder/claudemonet3.jpg', artist: 'Claude Monet' },
  { id: 'claudemonet4', imageUrl: 'Bilder/claudemonet4.jpg', artist: 'Claude Monet' },
  { id: 'claudemonet5', imageUrl: 'Bilder/claudemonet5.jpg', artist: 'Claude Monet' },
  { id: 'claudemonet6', imageUrl: 'Bilder/claudemonet6.jpg', artist: 'Claude Monet' },
  { id: 'claudemonet7', imageUrl: 'Bilder/claudemonet7.jpg', artist: 'Claude Monet' },
  { id: 'claudemonet8', imageUrl: 'Bilder/claudemonet8.jpg', artist: 'Claude Monet' },

  { id: 'salvadordali1', imageUrl: 'Bilder/salvadordali1.jpg', artist: 'Salvador Dali' },
  { id: 'salvadordali3', imageUrl: 'Bilder/salvadordali3.jpg', artist: 'Salvador Dali' },
  { id: 'salvadordali4', imageUrl: 'Bilder/salvadordali4.jpg', artist: 'Salvador Dali' },
  { id: 'salvadordali5', imageUrl: 'Bilder/salvadordali5.jpg', artist: 'Salvador Dali' },
  { id: 'salvadordali6', imageUrl: 'Bilder/salvadordali6.jpg', artist: 'Salvador Dali' },
  { id: 'salvadordali7', imageUrl: 'Bilder/salvadordali7.jpg', artist: 'Salvador Dali' },
  { id: 'salvadordali8', imageUrl: 'Bilder/salvadordali8.jpg', artist: 'Salvador Dali' },
  { id: 'salvadordali9', imageUrl: 'Bilder/salvadordali9.jpg', artist: 'Salvador Dali' },
  { id: 'salvadordali10', imageUrl: 'Bilder/salvadordali10.jpg', artist: 'Salvador Dali' },

  { id: 'diegovelazquez1', imageUrl: 'Bilder/diegovelázquez1.jpg', artist: 'Diego Velázquez' },
  { id: 'diegovelazquez2', imageUrl: 'Bilder/diegovelázquez2.jpg', artist: 'Diego Velázquez' },
  { id: 'diegovelazquez3', imageUrl: 'Bilder/diegovelázquez3.jpg', artist: 'Diego Velázquez' },
  { id: 'diegovelazquez4', imageUrl: 'Bilder/diegovelázquez4.jpg', artist: 'Diego Velázquez' },
  { id: 'diegovelazquez5', imageUrl: 'Bilder/diegovelázquez5.jpg', artist: 'Diego Velázquez' },
  { id: 'diegovelazquez6', imageUrl: 'Bilder/diegovelázquez6.jpg', artist: 'Diego Velázquez' },
  { id: 'diegovelazquez7', imageUrl: 'Bilder/diegovelázquez7.jpg', artist: 'Diego Velázquez' },
  { id: 'diegovelazquez8', imageUrl: 'Bilder/diegovelázquez8.jpg', artist: 'Diego Velázquez' },
  { id: 'diegovelazquez9', imageUrl: 'Bilder/diegovelázquez9.jpg', artist: 'Diego Velázquez' },
  { id: 'diegovelazquez10', imageUrl: 'Bilder/diegovelázquez10.jpg', artist: 'Diego Velázquez' },

  { id: 'pablopicasso1', imageUrl: 'Bilder/pablopicasso1.jpg', artist: 'Pablo Picasso' },
  { id: 'pablopicasso2', imageUrl: 'Bilder/pablopicasso2.jpg', artist: 'Pablo Picasso' },
  { id: 'pablopicasso3', imageUrl: 'Bilder/pablopicasso3.jpg', artist: 'Pablo Picasso' },
  { id: 'pablopicasso4', imageUrl: 'Bilder/pablopicasso4.jpg', artist: 'Pablo Picasso' },
  { id: 'pablopicasso5', imageUrl: 'Bilder/pablopicasso5.jpg', artist: 'Pablo Picasso' },
  { id: 'pablopicasso6', imageUrl: 'Bilder/pablopicasso6.jpg', artist: 'Pablo Picasso' },
  { id: 'pablopicasso7', imageUrl: 'Bilder/pablopicasso7.jpg', artist: 'Pablo Picasso' },
  { id: 'pablopicasso8', imageUrl: 'Bilder/pablopicasso8.jpg', artist: 'Pablo Picasso' },
  { id: 'pablopicasso9', imageUrl: 'Bilder/pablopicasso9.jpg', artist: 'Pablo Picasso' },
  { id: 'pablopicasso10', imageUrl: 'Bilder/pablopicasso10.jpg', artist: 'Pablo Picasso' },

  { id: 'rembrandt1', imageUrl: 'Bilder/rembrandt1.png', artist: 'Rembrandt' },
  { id: 'rembrandt2', imageUrl: 'Bilder/rembrandt2.png', artist: 'Rembrandt' },
  { id: 'rembrandt3', imageUrl: 'Bilder/rembrandt3.png', artist: 'Rembrandt' },
  { id: 'rembrandt4', imageUrl: 'Bilder/rembrandt4.png', artist: 'Rembrandt' },
  { id: 'rembrandt5', imageUrl: 'Bilder/rembrandt5.png', artist: 'Rembrandt' },
  { id: 'rembrandt6', imageUrl: 'Bilder/rembrandt6.png', artist: 'Rembrandt' },
  { id: 'rembrandt7', imageUrl: 'Bilder/rembrandt7.png', artist: 'Rembrandt' },
  { id: 'rembrandt8', imageUrl: 'Bilder/rembrandt8.png', artist: 'Rembrandt' },
  { id: 'rembrandt9', imageUrl: 'Bilder/rembrandt9.png', artist: 'Rembrandt' },
  { id: 'rembrandt10', imageUrl: 'Bilder/rembrandt10.png', artist: 'Rembrandt' }
];
